/* Copyright (C) Heng Ye - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Heng Ye <leonyhenn@gmail.com>, July 2019
 */
export var Lan;

export function setLanDict(language){
  if (language == "Chinese"){

  // Login
  Lan = {
   'Access_via_WeChat' : "用微信登录",
   'Access_via_FaceBook' : "用脸书登录",
   'Encryption_claim' : "您的微信/脸书账号在进入我们的数据库前会被不可逆加密,请不用担心使用MASKOFF可能带来的社交账号泄露问题.",
   'Legal_claim' : "继续代表您同意我们的服务协议",
  // General Navigator
   'Maskers' : "实锤",
   'Roasts' : "吐槽",
   'Contacts' : "联系人",
   'You' : "你",
  // Navigator Roast/Masker
   'Follow' : "跟进",
   'Recommand' : "推荐",
   'Trending' : "当前正火",
   'Around' : "附近",
   'Theirs' : "步行街",
   'Him' : "查他",
  // Navigator Chat
   'Recent' : "最近",
   'Notices' : "系统消息",
   'Them' : "联络人查询",
  // Display card
   'Contributed_count' : "标注",
   'Likes' : "点赞",
   'Comments' : "评论",
   'Comments_section' : "评论区",
  // Side menu
   'Chat_author' : "私信",
   'See_more' : "看更多",
   'Talk_to_group' : "和作者们谈谈",
   'I_know_more' : "我也认识他",
   'Update_article' : "更新文章",
   'Delete_article' : "删除文章",
   'Block' : "拉黑",
   'Report' : "举报",
   'Download':"下载",
   'Share':"转发",
   // Button Header
   'Post' : "发表",
   'Back' : "返回",
   'Next' : "下一步",
   'Preview' : "预览",
   'Publish' : "发布",
   'SMS_Verify':"短信验证",
   // Textinput Placeholder
    // Post_name_alias.js
   'Please_enter_his_name' : "请输入对方的名字(必填)" ,
   'Please_enter_his_alias' : "对方有什么别名吗? 比如英文名",
   // Disclaimer
   'Post_Verify_Disclaimer_1' : "我们需要知道您是一个真人",
   'Post_Verify_Disclaimer_2' : "同您的社交账号一样, 您的电话号码在进入我们的数据库之前也会进行不可逆加密",
   //InputToolBar
   'Tools':"工具栏",
   'Text':"文字",
   'Picture':"图片",
   'Video':"视频",
   'Fold':"折叠",
   'Screen':"屏幕",
   'Recorder':"录制",
   'Location':"地点",
   'Vote':"投票",
   'Vote_success':"投票成功!",
   // Phone Verification
   'Send_Verification_Code' : "发送验证码",
   'Resend' : "重新发送",
   'Confirm' : "确认",
   'Retry_in' : "后重试",
   'Too_soon' : "要求发送验证码过快，请稍后重试。",
   'Invalid_code' : "验证码无效, 请重试",
   // Post
   'No_name_alert' : "请输入他的姓名以方便他人查询,\n\n如果不知道他的真名的话外号或者英文名也可以",
   'No_content_alert' : '请点击"工具栏"来输入一些内容',
   'Reminder_window' : "开炮吧!",
   'Tags' : "请输入对方的一些标签,方便他人定位(必填)",
   'Tags_roast' : "请给这条吐槽加上一些标签",
   'As' : "别名",
   'Tag' : "标签",
   'Title' : "给你的吐槽起一个标题",
   'No_title_alert' : "吐槽需要一个标题哟",
   // Http Reqs
   'Post_Failed' : "发布失败",
   'Post_Success' : "发布成功!",
   'Done' : "完成",
   'OK' : "知道了",
   'No_Internet' : "无网络链接",
   'Retry' : "再次尝试",
   'No_Internet_mes' : "无法连接上服务器",
   // Map
   'Location_Cancel' : "轻按来取消",
   'Location_Confirm' : "轻按此来确认发送",
   'Location_Send_Confirm' : "你将要发送这个位置",
   'Wait' : "等等....",
   'Cancel' : "取消",
   'Empty_Results_Roast' : '抱歉, 还没有人Po关于这些的吐槽呢, 要不你来吐槽一个吧!',
   'Empty_Results_Masker' : "这老铁看着没毛病...",
   'Empty_Comments' : "还没有人评论呢, 不来一发吗?",
   'Use_space_seperate_alias' : "不同的别名请用空格隔开",
   'Use_space_seperate_tags' : "不同的标签请用空格隔开",
   'Delete' : "删除",
   'Add' : "添加",
   'Input_here' : "在这里输入选项",
   'More_articles_about_this_masker_front' : "更多有关于",
   'More_articles_about_this_masker_back' : "的文章",
   'Chat_Picture_Send_Confirm' : "你确定要发送这张图片?",
   'Chat_Video_Send_Confirm' : "你确定要发送这个视频?",
   'edit_profile_picture_masker' : "编辑实锤区头像",
   'edit_profile_picture_roast' : "编辑吐槽区头像",
   'Chinese_English_Conversion' : '中/英切换',
   'Closing_Account' : '关闭账户',
   'About_MASKOFF' : '关于MASKOFF',
   'Blocklist' : '黑名单',
   'Notification_Sound' : '消息提醒 - 声音',
   'Notification_Vibration' : '消息提醒 - 振动',
   'UnBlackList' : "解除拉黑",
   'Law' : "MASKOFF用户协议",
   'Developed_by' : 'MASKOFF团队开发',
   'Confirm_Close_Account' : '你确定要关闭账号吗?',
   'Close_Account_Done' : '您的账号已被关闭',
   'Lose_all_info' : "如果关闭账号, 您的账号将被设置为不可见, 且您不会再接收到消息",
   'Delete_Chat' : "删除聊天",
   'Bad_Response':"服务器无响应",
   'Need_location_perm_message':"我们需要您准许我们获取您的位置来开启'附近' 功能.\n\n MASKOFF不会在后台记录您的位置信息,请放心准许.\n\n 如误按请去设置中打开位置准许.",
   'Need_location_perm_title':"位置准许-下个窗口请按右键",
   'Terms':"服务条款",
   //MO_Alert
   'Phone_Num_Not_Numeric':"你输入的电话号码中有非数字字符",
   'Country_Code_Not_Numeric':"你输入的国家代码中有非数字字符",
   'Maxmun_length_exceeded':'一个段落请不要超过2000字哟',
   'Screen_Recorder_Instruction':'因为系统限制, App暂时不支持自带屏幕录制, 请使用安卓/ios系统自带的屏幕录制, 可以以视频的方式传上来哦',
   'handleVoteTwice':'一篇文章只能有一个投票区哦',
   'updateVoteRejection':'已发布的文章不能更改投票区, 但可以删除',
   'You_Are_The_Author':'您就是作者',
   //Time Function
   'Years_ago':'年前',
   'Half_Year_ago':'大半年前',
   'Months_ago':'月前',
   'Weeks_ago':'周前',
   'Days_ago':'天前',
   'Hours_ago':'小时前',
   'Minutes_ago':'分钟前',
   "Search_in_MASKOFF":"在MASKOFF中搜索",
   "Your_Maskers":"你的实锤",
   "Your_Roasts":"你的吐槽",
   //notification bar
   "documentDirectory/":"内部储存/",
   //placeHolder
   "Message":" 按此输入...",
   "Copy":"复制",
   "From_MASKOFF":"来自 MASKOFF",
   "Reply":"回复",
   "click_to_see_more":"点击查看更多",
   "cannot_find_file":"有些文件在您的文件系统中找不到...",
   "Image_over_size":"这个图像太大啦,有小一点的吗?",
   "Submit":"提交",
   "Vote_conflict":"You have already voted",
   "Vote_empty":"至少选一个哦",
   "connecting":"连接中",
   "first_time":"不好意思, 第一次, 没经验 😅"
 }
}else{

  // Login
  Lan = {
  'Access_via_WeChat' : "Access via WeChat",
  'Access_via_FaceBook' : "Access via Facebook",
  'Encryption_claim' : "Your Facebook/WeChat info will be irreversiblly encrypted, there is no ground for axiety in MASKOFF.",
  'Legal_claim' : "By continuing you indicate that you have read and agree to the Terms of Service.",
  // General Navigator
  'Maskers' : "Maskers",
  'Roasts' : "Roasts",
  'Contacts' : "Contacts",
  'You' : "You",
  // Navigator Roast/Masker
  'Follow' : "Follow",
  'Recommand' : "Recommand",
  'Around' : "Around",
  'Trending' : "Trending",
  'Theirs' : "Theirs",
  'Him' : "Him",
  // Navigator Chat
  'Recent' : "Recent",
  'Notices' : "Notices",
  'Them' : "Them",
  // Dislay card
  'Contributed_count' : "Contributed",
  'Likes' : "Likes",
  'Comments' : "Comments",
  // Side menu
  'Chat_author' : "Chat author",
  'See_more' : "See more",
  'Talk_to_group' : "Talk to group",
  'I_know_more' : "I know more",
  'Update_article' : "Update article",
  'Delete_article' : "Delete article",
  'Block' : "Blacklist this user",
  'Report' : "Report this user",
  'Download':"Download",
  'Share':"Share",
  // Button Header
  'Post' : "Post",
  'Back' : "Back",
  'Next' : "Next",
  'Preview' : "Preview",
  'Publish' : "Publish",
  'SMS_Verify':"SMS Verification",
  // Textinput Placeholder
    // Post_name_alias.js
  'Please_enter_his_name' : "Please enter his name(required)" ,
  'Please_enter_his_alias' : "Please enter his alias",
  // Disclaimer
  'Post_Verify_Disclaimer_1' : "We need to know you are a real person first. ",
  'Post_Verify_Disclaimer_2' : "Your phone number will be irreversiblly encrypted before enter our database.",
  //InputToolBar
  'Tools':"Tools",
  'Text':"Text",
  'Picture':"Picture",
  'Video':"Video",
  'Fold':"Fold",
  'Screen':"Screen",
  'Recorder':"Recorder",
  'Location':"Location",
  'Vote':"Vote",
  'Vote_success':"Vote success!",
  // Verification
  'Send_Verification_Code' : "Send Verification Code",
  'Resend' : "Resend",
  'Confirm' : "Confirm",
  'Retry_in' : "Retry in" ,
  'Too_soon' : "Request verification too soon, please try again later",
  'Invalid_code' : "Verification code is invalid, please try again",
  // Post
  'No_name_alert' : "please input his name so that others can search him.\n\nIf you don't know his real name, nickname would also do.",
  'No_content_alert' : 'please input some content by clicking on "Tools"',
  'Reminder_window' : "Now it's time to fire away !",
  'Tags' : "Please insert some tags so others can identify this person.(required)",
  'Tags_roast' : "Please insert some tags to your roast.",
  'As' : "As",
  'Tag' : "Tags",
  'Title' : "Please add a title to your roast",
  'No_title_alert' : "a Roast needs its title",
  // Http Reqs
  'Post_Failed' : "Post failed",
  'Post_Success' : "Post succeed",
  'Done' : "Done",
  'OK' : "OK",
  'No_Internet' : "No Internet",
  'Retry' : "Retry",
  'No_Internet_mes' : "Cannot connect to server",
  // Map
  'Location_Cancel' : "Tap to cancel",
  'Location_Confirm' : "Tap this to send",
  'Location_Send_Confirm' : "You are going to send this location",
  'Wait' : "Wait....",
  'Cancel' : "Cancel",
  'Empty_Results_Roast' : "No one has ever roasted this topic, why don't you be the first one?",
  'Empty_Results_Masker' : "Looks like he is safe, for now...",
  'Empty_Comments' : "No comments yet, come on!",
  'Use_space_seperate_alias' : "Please use space to seperate alias",
  'Use_space_seperate_tags' : "Please use space to seperate tags",
  'Delete' : "Delete",
  'Add' : "Add",
  'Input_here' : "Add first vote option here",
  'More_articles_about_this_masker_front' : "More articles about this masker",
  'More_articles_about_this_masker_back' : "",
  'Chat_Picture_Send_Confirm' : "You are going to send this picture",
  'Chat_Video_Send_Confirm' : "You are going to send this video",
  'edit_profile_picture_masker' : "Edit profile picture\n in Masker section",
  'edit_profile_picture_roast' : "Edit profile picture\n in Roast section",
  'Chinese_English_Conversion' : 'Chinese English Conversion',
  'Closing_Account' : 'Close account',
  'About_MASKOFF' : 'About MASKOFF',
  'Blocklist' : 'Block list',
  'Notification_Sound' : 'Notification - Sound',
  'Notification_Vibration' : 'Notification - Vibration',
  'UnBlackList' : "Unblock this user",
  'Law' : "MASKOFF User terms",
  'Developed_by' : 'Developed by MASKOFF group',
  'Confirm_Close_Account' : 'Are you sure to close this account?',
  'Close_Account_Done' : 'Your Account has already been closed',
  'Lose_all_info' : "If you want to close this account, you will no longer to receive messages and the account will be set to invisible",
  'Delete_Chat' : "Delete this chat",
  'Bad_Response':"Bad Response from server",
  'Need_location_perm_message':"We need your permission to Enable 'nearby' function in next popup window.\n\n If you have privacy concerns, MASKOFF will not record your location.\n\n If denined please go to 'Settings' to enable it.",
  'Need_location_perm_title':"Location Permission",
  'Terms':"Terms and Conditions",
  //MO_Alert
  'Phone_Num_Not_Numeric':"The input phone number contains non-numeric characters.",
  'Country_Code_Not_Numeric':"The input country code contains non-numeric characters.",
  'Maxmun_length_exceeded':"Please don't exceed the maximum length per paragraph (2000 words)",
  'Screen_Recorder_Instruction':'Screen recording inside app is temporary unavailable due to system limitation. Please record screen with system provided modules and upload it as a video.',
  'handleVoteTwice':'One article can only have one vote.',
  'updateVoteRejection':'an published article cannot update vote section, but you can delete it.',
  'You_Are_The_Author':'You are the author',
  //Time Function
  'Years_ago':' yrs ago',
  'Half_Year_ago':'> 6 mths ago',
  'Months_ago':' mths ago',
  'Weeks_ago':' wks ago',
  'Days_ago':' ds ago',
  'Hours_ago':' hrs ago',
  'Minutes_ago':' mins ago',
  "Search_in_MASKOFF":"Search in MASKOFF",
  "Your_Maskers":"Your Maskers",
  "Your_Roasts":"Your Roasts",
  //notification bar
  "documentDirectory/":"Internal storage/",
  "Message":" Message",
  "Copy":"Copy",
  "From_MASKOFF":"From MASKOFF",
  "Reply":"Reply",
  "click_to_see_more":"Click to see more",
  "cannot_find_file":"Some files cannot be found in your file system...",
  "Image_over_size":"This image has an unexpected height or width",
  "Submit":"Submit",
  "Vote_conflict":"You have already voted",
  "Vote_empty":"The vote is empty",
  "connecting":"connecting...",
  "first_time":"Sorry, it's also my first time 😅"
  }
}

}
